const DB_NAME='dalzzal-album-pwa'; const DB_VERSION=1; const STORE='state';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state={folders:[],entries:[],theme:'light',generatorBlocks:['boy, solo, male focus','1.25::toned male::','black hair, short hair','school uniform','classroom background']};
let view={folderId:null,filter:'all',tag:null,query:''}; let workingImages=[];
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function loadState(){const db=await openDB();const val=await new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly');const r=t.objectStore(STORE).get('app');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(val)state=val;applyTheme();renderAll()}
async function saveState(){const db=await openDB();await new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(state,'app');t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark');$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾'}
function folderMap(){return new Map(state.folders.map(f=>[f.id,f]))}
function folderPath(id){if(!id)return '전체 프롬프트';const map=folderMap();const parts=[];let cur=map.get(id),guard=0;while(cur&&guard++<20){parts.unshift(cur.name);cur=cur.parentId?map.get(cur.parentId):null}return parts.join(' / ')||'전체 프롬프트'}
function descendantIds(id){const out=new Set([id]);let changed=true;while(changed){changed=false;state.folders.forEach(f=>{if(f.parentId&&out.has(f.parentId)&&!out.has(f.id)){out.add(f.id);changed=true}})}return out}
function renderAll(){renderFolders();renderFolderSelects();renderTags();renderEntries();renderGenerator()}
function renderFolders(){const tree=$('#folderTree');const children=parent=>state.folders.filter(f=>(f.parentId||null)===(parent||null)).sort((a,b)=>a.name.localeCompare(b.name,'ko'));function branch(parent,depth=0){return children(parent).map(f=>`<div class="${depth?'folder-indent':''}"><div class="folder-item ${view.folderId===f.id?'active':''}" data-id="${f.id}"><button class="folder-main" data-folder="${f.id}">📁 ${esc(f.name)}</button><span class="folder-actions"><button data-fedit="${f.id}">✎</button><button data-fdel="${f.id}">×</button></span></div>${branch(f.id,depth+1)}</div>`).join('')}tree.innerHTML=`<div class="folder-item ${view.folderId===null?'active':''}"><button class="folder-main" data-folder="">◉ 전체</button></div>`+branch(null);$$('[data-folder]').forEach(b=>b.onclick=()=>{view.folderId=b.dataset.folder||null;view.tag=null;renderAll()});$$('[data-fedit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openFolderDialog(b.dataset.fedit)});$$('[data-fdel]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteFolder(b.dataset.fdel)})}
function renderFolderSelects(){for(const sel of [$('#entryFolder'),$('#folderParent')]){if(!sel)continue;const current=sel.value;sel.innerHTML='<option value="">없음 / 전체</option>'+state.folders.map(f=>`<option value="${f.id}">${'— '.repeat(depthOf(f.id))}${esc(f.name)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current}}
function depthOf(id){const map=folderMap();let n=0,cur=map.get(id),guard=0;while(cur?.parentId&&guard++<20){n++;cur=map.get(cur.parentId)}return n}
function currentEntries(){let entries=state.entries.filter(e=>view.filter==='trash'?e.trashed:!e.trashed);if(view.filter==='favorite')entries=entries.filter(e=>e.favorite);if(view.folderId){const ids=descendantIds(view.folderId);entries=entries.filter(e=>ids.has(e.folderId))}if(view.tag)entries=entries.filter(e=>(e.tags||[]).includes(view.tag));const q=view.query.trim().toLowerCase();if(q)entries=entries.filter(e=>[e.title,e.prompt,e.negative,(e.tags||[]).join(' ')].join(' ').toLowerCase().includes(q));return entries.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt))}
function renderTags(){const base=state.entries.filter(e=>!e.trashed && (!view.folderId||descendantIds(view.folderId).has(e.folderId)));const counts={};base.forEach(e=>(e.tags||[]).forEach(t=>counts[t]=(counts[t]||0)+1));const tags=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,20);$('#tagCloud').innerHTML=tags.map(([t,c])=>`<button class="tag-pill ${view.tag===t?'active':''}" data-tag="${esc(t)}">#${esc(t)} ${c}</button>`).join('');$$('[data-tag]').forEach(b=>b.onclick=()=>{view.tag=view.tag===b.dataset.tag?null:b.dataset.tag;renderTags();renderEntries()})}
function renderEntries(){const entries=currentEntries();$('#entryCount').textContent=`${entries.length}개`;$('#currentFolderLabel').textContent=view.filter==='trash'?'휴지통':folderPath(view.folderId);$('#emptyState').classList.toggle('hidden',entries.length>0);$('#entryGrid').innerHTML=entries.map(e=>{const img=e.images?.[0];return `<article class="entry-card"><button class="card-open" data-open="${e.id}"><div class="thumb">${img?`<img src="${img}" alt="">`:'✦'}${e.images?.length>1?`<span class="image-count">+${e.images.length-1}</span>`:''}${e.favorite?'<span class="fav-star">★</span>':''}</div><div class="card-body"><div class="entry-title-row"><div class="entry-title">${esc(e.title||'제목 없음')}</div><span class="type-badge">${esc(e.type||'기타')}</span></div><div class="prompt-preview">${esc(e.prompt||e.negative||'프롬프트 없음')}</div><div class="card-tags">${(e.tags||[]).slice(0,4).map(t=>`<span class="card-tag">#${esc(t)}</span>`).join('')}</div><div class="card-footer"><span>${new Date(e.updatedAt).toLocaleDateString('ko-KR')}</span><span>${esc(folderPath(e.folderId).split(' / ').pop())}</span></div></div></button><div class="card-actions">${view.filter==='trash'?`<button data-restore="${e.id}">복원</button><button data-harddel="${e.id}">영구삭제</button>`:`<button data-edit="${e.id}">수정</button><button data-trash="${e.id}">삭제</button>`}</div></article>`}).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open));$$('[data-edit]').forEach(b=>b.onclick=()=>openEntryDialog(b.dataset.edit));$$('[data-trash]').forEach(b=>b.onclick=()=>trashEntry(b.dataset.trash));$$('[data-restore]').forEach(b=>b.onclick=()=>restoreEntry(b.dataset.restore));$$('[data-harddel]').forEach(b=>b.onclick=()=>hardDeleteEntry(b.dataset.harddel))}
function openEntryDialog(id=null,prefill=null){const e=id?state.entries.find(x=>x.id===id):null;$('#entryDialogTitle').textContent=e?'프롬프트 수정':'새 프롬프트';$('#entryId').value=e?.id||'';$('#entryTitle').value=prefill?.title||e?.title||'';$('#entryType').value=e?.type||'NovelAI';renderFolderSelects();$('#entryFolder').value=e?.folderId||view.folderId||'';$('#entryPrompt').value=prefill?.prompt||e?.prompt||'';$('#entryNegative').value=e?.negative||'';$('#entryTags').value=(e?.tags||[]).join(', ');$('#entryFavorite').checked=!!e?.favorite;workingImages=[...(e?.images||[])];renderImagePreview();$('#entryImages').value='';$('#entryDialog').showModal()}
function renderImagePreview(){$('#imagePreview').innerHTML=workingImages.map((src,i)=>`<div class="preview-item"><img src="${src}" alt=""><button type="button" data-rmimg="${i}">×</button></div>`).join('');$$('[data-rmimg]').forEach(b=>b.onclick=()=>{workingImages.splice(+b.dataset.rmimg,1);renderImagePreview()})}
async function filesToDataUrls(files){const out=[];for(const f of files){out.push(await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)}))}return out}
async function submitEntry(ev){ev.preventDefault();const id=$('#entryId').value;const now=new Date().toISOString();const item={id:id||uid(),title:$('#entryTitle').value.trim(),type:$('#entryType').value,folderId:$('#entryFolder').value||null,prompt:$('#entryPrompt').value,negative:$('#entryNegative').value,tags:$('#entryTags').value.split(',').map(x=>x.trim()).filter(Boolean),images:workingImages,favorite:$('#entryFavorite').checked,trashed:false,createdAt:now,updatedAt:now};if(id){const old=state.entries.find(x=>x.id===id);Object.assign(item,{createdAt:old.createdAt,trashed:old.trashed});state.entries[state.entries.findIndex(x=>x.id===id)]=item}else state.entries.push(item);await saveState();$('#entryDialog').close();renderAll()}
function openFolderDialog(id=null){const f=id?state.folders.find(x=>x.id===id):null;$('#folderDialogTitle').textContent=f?'폴더 수정':'폴더 추가';$('#folderId').value=f?.id||'';$('#folderName').value=f?.name||'';renderFolderSelects();$('#folderParent').value=f?.parentId||'';if(id){[...$('#folderParent').options].forEach(o=>{if(o.value===id||descendantIds(id).has(o.value))o.disabled=true})}$('#folderDialog').showModal()}
async function submitFolder(ev){ev.preventDefault();const id=$('#folderId').value;const obj={id:id||uid(),name:$('#folderName').value.trim(),parentId:$('#folderParent').value||null};if(id)state.folders[state.folders.findIndex(f=>f.id===id)]=obj;else state.folders.push(obj);await saveState();$('#folderDialog').close();renderAll()}
async function deleteFolder(id){if(!confirm('폴더를 삭제할까요? 안의 프롬프트는 전체로 이동합니다.'))return;const ids=descendantIds(id);state.entries.forEach(e=>{if(ids.has(e.folderId))e.folderId=null});state.folders=state.folders.filter(f=>!ids.has(f.id));if(view.folderId&&ids.has(view.folderId))view.folderId=null;await saveState();renderAll()}
async function trashEntry(id){const e=state.entries.find(x=>x.id===id);if(!e)return;e.trashed=true;e.updatedAt=new Date().toISOString();await saveState();renderAll()}
async function restoreEntry(id){const e=state.entries.find(x=>x.id===id);if(!e)return;e.trashed=false;e.updatedAt=new Date().toISOString();await saveState();renderAll()}
async function hardDeleteEntry(id){if(!confirm('영구 삭제하면 복구할 수 없어요. 계속할까요?'))return;state.entries=state.entries.filter(x=>x.id!==id);await saveState();renderAll()}
function openDetail(id){const e=state.entries.find(x=>x.id===id);if(!e)return;$('#detailBody').innerHTML=`<div class="muted">${esc(e.type)} · ${esc(folderPath(e.folderId))}</div><h2 class="detail-title">${esc(e.title)}</h2><div class="card-tags">${(e.tags||[]).map(t=>`<span class="card-tag">#${esc(t)}</span>`).join('')}</div>${e.images?.length?`<div class="detail-gallery">${e.images.map(x=>`<img src="${x}" alt="">`).join('')}</div>`:''}<h3>프롬프트</h3><div class="detail-prompt">${esc(e.prompt||'')}</div>${e.negative?`<h3>네거티브 / 메모</h3><div class="detail-prompt">${esc(e.negative)}</div>`:''}<div class="detail-actions"><button data-copy-prompt="${e.id}">프롬프트 복사</button><button data-togglefav="${e.id}">${e.favorite?'★ 즐겨찾기 해제':'☆ 즐겨찾기'}</button><button data-detail-edit="${e.id}">수정</button><button class="danger" data-detail-trash="${e.id}">휴지통</button></div>`;$('#detailDialog').showModal();$('[data-copy-prompt]').onclick=()=>copyText(e.prompt);$('[data-togglefav]').onclick=async()=>{e.favorite=!e.favorite;await saveState();$('#detailDialog').close();renderAll()};$('[data-detail-edit]').onclick=()=>{$('#detailDialog').close();openEntryDialog(e.id)};$('[data-detail-trash]').onclick=async()=>{$('#detailDialog').close();await trashEntry(e.id)}}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('복사했어요')}catch{const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('복사했어요')}}
function toast(msg){const d=document.createElement('div');d.textContent=msg;d.style.cssText='position:fixed;left:50%;bottom:90px;transform:translateX(-50%);background:#222;color:#fff;padding:10px 14px;border-radius:999px;z-index:9999;font-size:13px';document.body.appendChild(d);setTimeout(()=>d.remove(),1600)}
function renderGenerator(){const wrap=$('#generatorBlocks');if(!wrap)return;wrap.innerHTML='';(state.generatorBlocks||[]).forEach(v=>addGeneratorBlock(v));updateGeneratorResult()}
function addGeneratorBlock(value=''){const tpl=$('#generatorBlockTpl').content.cloneNode(true);const row=tpl.querySelector('.generator-block');const input=row.querySelector('input[type=text]');input.value=value;row.querySelector('input[type=checkbox]').onchange=updateGeneratorResult;input.oninput=()=>{syncGeneratorState();updateGeneratorResult()};row.querySelector('.remove-block').onclick=()=>{row.remove();syncGeneratorState();updateGeneratorResult()};$('#generatorBlocks').appendChild(row)}
function syncGeneratorState(){state.generatorBlocks=$$('.generator-block input[type=text]').map(x=>x.value);saveState()}
function updateGeneratorResult(){const rows=$$('.generator-block');$('#generatorResult').value=rows.filter(r=>r.querySelector('input[type=checkbox]').checked).map(r=>r.querySelector('input[type=text]').value.trim()).filter(Boolean).join(',\n')}
async function exportBackup(){const blob=new Blob([JSON.stringify({...state,_ganggyeramBackup:true,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`강계람_백업_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(!data._ganggyeramBackup&&!data._dalzzalBackup&&!Array.isArray(data.entries))throw new Error('강계람 백업 파일이 아닙니다.');if(!confirm('현재 데이터를 백업 파일로 덮어쓸까요?'))return;state={folders:data.folders||[],entries:data.entries||[],theme:data.theme||'light',generatorBlocks:data.generatorBlocks||[]};await saveState();applyTheme();renderAll();$('#settingsDialog').close();toast('백업을 불러왔어요')}catch(e){alert('불러오기 실패: '+e.message)}}
async function seed(){const f1={id:uid(),name:'캐릭터',parentId:null},f2={id:uid(),name:'학교',parentId:f1.id};state.folders.push(f1,f2);state.entries.push({id:uid(),title:'봄 교실 미소',type:'NovelAI',folderId:f2.id,prompt:'boy, solo, male focus, black hair, short hair, school uniform, classroom, spring, gentle smile',negative:'low quality, bad hands',tags:['남캐','교복','봄'],images:[],favorite:true,trashed:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await saveState();renderAll();toast('예시 데이터를 추가했어요')}
function closeDialogs(){/* no-op */}
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#entryForm').addEventListener('submit',submitEntry);$('#folderForm').addEventListener('submit',submitFolder);$('#entryImages').addEventListener('change',async e=>{workingImages.push(...await filesToDataUrls(e.target.files));renderImagePreview()});
$('#addEntryBtn').onclick=()=>openEntryDialog();$('#fab').onclick=()=>openEntryDialog();$('#addFolderBtn').onclick=()=>openFolderDialog();
$('#searchInput').oninput=e=>{view.query=e.target.value;renderEntries()};$('#clearSearchBtn').onclick=()=>{$('#searchInput').value='';view.query='';renderEntries()};
$$('#filterTabs .chip').forEach(b=>b.onclick=()=>{$$('#filterTabs .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');view.filter=b.dataset.filter;renderTags();renderEntries()});
$('#themeBtn').onclick=async()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();await saveState()};
$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#exportBtn').onclick=exportBackup;$('#importInput').onchange=e=>{const f=e.target.files[0];if(f)importBackup(f);e.target.value=''};$('#seedBtn').onclick=seed;$('#clearAllBtn').onclick=async()=>{if(!confirm('모든 데이터를 정말 삭제할까요?'))return;state={folders:[],entries:[],theme:state.theme,generatorBlocks:[]};await saveState();renderAll();toast('모든 데이터를 삭제했어요')};
$('#generatorBtn').onclick=()=>{$('#generatorDialog').showModal();renderGenerator()};$('#addGeneratorBlock').onclick=()=>{addGeneratorBlock('');syncGeneratorState()};$('#copyGeneratorBtn').onclick=()=>copyText($('#generatorResult').value);$('#saveGeneratedBtn').onclick=()=>{const p=$('#generatorResult').value;$('#generatorDialog').close();openEntryDialog(null,{title:'생성된 프롬프트',prompt:p})};
['input','change'].forEach(ev=>$('#generatorBlocks').addEventListener(ev,updateGeneratorResult));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
loadState();
